export interface Order {
  id: number;
  order_id: number;
  order_datetime: string;
  status: string;
  price: string;
  first_name: string;
  last_name: string;
  shipping_type: string;
  delivery_time: string;
  produit: number;
  produit2?: number;
  typeCommande: string;
  typeCorrection: string;
  origineArticle: string;
  article_libelle?: string;
  sphere?: number;
  cylindre?: number;
  addition?: number;
  selected_file?: string;
  fournisseur_id?: number;
  payment_status?: string;
  od_sphere?: string;
  od_cylinder?: string;
  od_addition?: string;
  od_axe?: string;
  og_sphere?: string;
  og_cylinder?: string;
  og_addition?: string;
  og_axe?: string;
  raison_social?: string;
  fournisseur_code?: string;
  article_id?: number;
  fabrication1?: number;
  fabrication2?: number;
  [key: string]: any;
} 